# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Version Properties
minecraft_version=1.20.1
parchment_mappings=2023.09.03
fabric_loader_version=0.19.5
fabric_loom_version=1.17-SNAPSHOT

# Mod Properties
mod_id=minelittleflawless
mod_name=Mine Little Flawless
mod_license=MIT
mod_version=0.5.0-dev.7
mod_group_id=org.projectflawless.minelittleflawless
mod_authors=SymphonyDawn3
mod_description=In this Minecraft mod, you will experience the ways that you can make friends, defeat foes, and conquer your Minecraft world with Mine Little Flawless!
mod_homepage=https://github.com/SymphonyDawn3/MineLittleFlawless
mod_issues=https://github.com/SymphonyDawn3/MineLittleFlawless/issues
mod_icon=icon.png
archives_name = minelittleflawless
enabled_platforms = fabric,forge

# Dependencies
fabric_api_version=0.92.12+1.20.1
forge_version=1.20.1-47.4.10
architectury_api_version=9.2.14
mixinextras_version=0.5.4
sbl_version=1.15
modmenu_version=7.2.2
geckolib_version=4.8.4